# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Build-repo:
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 Building the project"
  ServiceNow-Change-Management:
    needs: Build-repo
    runs-on: ubuntu-latest
    steps: 
      - name: Test 
        env: 
          EMPSNRAO_TOKEN : ${{ secrets.EMPSNRAO_TOKEN }}
      - run: echo "🎉 The job was automatically triggered by a $EMPSNRAO_TOKEN event"          
      - name: ServiceNow DevOps Change Automation
        env: 
          EMPSNRAO_TOKEN : ${{ secrets.EMPSNRAO_TOKEN }}
        # You may pin to the exact commit or the version.
        # uses: ServiceNow/servicenow-devops-change@41fd6520fa5369e3098596eadec108fc809c37f8
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
          # ServiceNow Instance URL
          instance-url: "https://empsnrao1.service-now.com/"
          # Devops Integration User Name
          devops-integration-token: "$EMPSNRAO_TOKEN"
          # Orchestration Tool Id
          tool-id: "6b40e871c31539104395388f050131e1"
          # Display Name of the Job
          job-name: ServiceNow-Change-Management
          # Github Context
          context-github: 36000
          # The max. time in seconds to wait until the action should fail.
          change-request: 30000
          # The max. time in seconds to wait until change created.
  
